remote: origin
target-branch: main
chart-dirs:
  - operations/helm/charts
helm-extra-args: --timeout 600s
validate-maintainers: false
check-version-increment: false  # Don't require every change to be released
