version: "2"
services:
  agent:
    image: grafana/agent:latest
    volumes:
      - /tmp/agent:/tmp/agent
      - ./agent/config:/etc/agent-config
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent-scraping-service.yaml
      - -prometheus.wal-directory=/tmp/agent/wal
    ports:
      - "12345:12345"

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.7
    entrypoint:
      - /usr/local/bin/etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
      - --log-level=info

  cortex:
    image: cortexproject/cortex:v0.6.1
    volumes:
      - /tmp/cortex:/tmp/cortex
      - ./cortex/config:/etc/cortex-config
    entrypoint:
      - /bin/cortex
      - -config.file=/etc/cortex-config/cortex.yaml
    ports:
      - "9009:9009"

  grafana:
    image: grafana/grafana:6.6.1
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"

  avalanche-1:
    image: quay.io/freshtracks.io/avalanche:latest
  avalanche-2:
    image: quay.io/freshtracks.io/avalanche:latest
  avalanche-3:
    image: quay.io/freshtracks.io/avalanche:latest
  avalanche-4:
    image: quay.io/freshtracks.io/avalanche:latest
  avalanche-5:
    image: quay.io/freshtracks.io/avalanche:latest
