{{- if and (eq .Values.agent.mode "flow") (.Values.agent.clustering.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-agent.fullname" . }}-cluster
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: 'None'
  selector:
    {{- include "grafana-agent.selectorLabels" . | nindent 4 }}
  ports:
    # Do not include the -metrics suffix in the port name, otherwise metrics
    # can be double-collected with the non-headless Service if it's also
    # enabled.
    #
    # This service should only be used for clustering, and not metric
    # collection.
    - name: http
      port: {{ .Values.agent.listenPort }}
      targetPort: {{ .Values.agent.listenPort }}
      protocol: "TCP"
  {{- range $portMap := .Values.agent.extraPorts }}
    - name: {{ $portMap.name }}
      port: {{ $portMap.port }}
      targetPort: {{ $portMap.targetPort }}
      protocol: {{ coalesce $portMap.protocol "TCP" }}
  {{- end }}
{{- end }}
