{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: "{{ tpl $value $ | b64enc }}"
  {{- end }}
{{- end }}