# Test rendering of the chart with the global image pull secret explicitly set.
global:
  image:
    pullSecrets:
    - name: global-cred

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000

image:
  pullSecrets:
  - name: local-cred
