version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    ignore:
      # OpenTelemetry needs special handling due to a temporary fork; exempt
      # from Dependabot auto-updating.
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector-contrib/*"
      - dependency-name: "go.opentelemetry.io/collector"
      - dependency-name: "go.opentelemetry.io/collector/model"
  - package-ecosystem: "npm"
    directory: "/web/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
