# Full list of configuration options: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

output:
  sort-results: true

linters:
  enable:
    - deadcode    # Report on unused code
    - errcheck    # Report unchecked errors
    - goconst     # Find repeated strings that could be replaced by constant
    - gofmt       # Check whether code was gofmt-ed
    - goimports   # Check imports were formatted with gofmt
    - revive      # Broad set of rules; replaces deprecated golint
    - gosimple    # Check whether code can be simplified
    - ineffassign # Detect when assignment to variable is never used
    - misspell    # Report on commonly misspelled English words
    - structcheck # Report on unused struct fields
    - unconvert   # Remove unnecessary type conversions
    - unparam     # Detect unused function parameters
    - varcheck    # Find unused global variables/constants
    - govet       # `go vet`
    - unused      # Detect unused constants/variables/functions/types
    - typecheck   # Ensure code typechecks
    - depguard    # Allow/denylist specific imports
    - makezero    # Detect misuse of make with non-zero length and append
    - tenv        # Use testing.(*T).Setenv instead of os.Setenv
    - whitespace  # Report unnecessary blank lines

issues:
  # We want to use our own exclusion rules and ignore all the defaults.
  exclude-use-default: false

  exclude-rules:
    # It's fine if tests ignore errors.
    - path: _test.go
      linters:
        - errcheck

  exclude:
    # Ignoring errors on Close, Log, and removing files is OK in most cases.
    - "Error return value of `(.*\\.Close|.*\\.Log|os.Remove)` is not checked"
    # Packages for integrations are named matching their upstream counterpart,
    # which almost always have underscores.
    - "var-naming: don't use an underscore in package name"

# Linter settings options: https://golangci-lint.run/usage/linters/
linters-settings:
  depguard:
    # We want to report errors on stdlib packages, not just third party modules
    include-go-root: true

    packages-with-error-message:
      - sync/atomic: "Use go.uber.org/atomic instead of sync/atomic"
      - github.com/pkg/errors: "Use errors instead of github.com/pkg/errors"
      - github.com/go-kit/kit/log: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
      - golang.org/x/sync/errgroup: "Use github.com/oklog/run instead of golang.org/x/sync/errgroup"

  whitespace:
    # While there normally shouldn't be extra redundant leading/trailing
    # whitespace, if statement conditions and function headers that cross
    # multiple lines are an exception.
    #
    #   if true ||
    #      false {
    #
    #       // ... ^ must have empty line above
    #    }
    #
    #   func foo(
    #     a int,
    #   ) {
    #
    #     // ... ^ must have empty line above
    #   }
    #
    # This helps readers easily separate where the multi-line if/function ends
    # at a glance.
    multi-if: true
    multi-func: true

