---
# Source: grafana-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-grafana-agent
  labels:
    helm.sh/chart: grafana-agent-0.13.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v0.33.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: grafana-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-grafana-agent
  labels:
    helm.sh/chart: grafana-agent-0.13.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v0.33.1"
    app.kubernetes.io/managed-by: Helm
data:
  config.river: |-
    logging {
    	level  = "info"
    	format = "logfmt"
    }
    
    discovery.kubernetes "pods" {
    	role = "pod"
    }
    
    discovery.kubernetes "nodes" {
    	role = "node"
    }
    
    discovery.kubernetes "services" {
    	role = "service"
    }
    
    discovery.kubernetes "endpoints" {
    	role = "endpoints"
    }
    
    discovery.kubernetes "endpointslices" {
    	role = "endpointslice"
    }
    
    discovery.kubernetes "ingresses" {
    	role = "ingress"
    }
---
# Source: grafana-agent/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: RELEASE-NAME-grafana-agent
  labels:
    helm.sh/chart: grafana-agent-0.13.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v0.33.1"
    app.kubernetes.io/managed-by: Helm
rules:
  # Rules which allow discovery.kubernetes to function.
  - apiGroups:
      - ""
      - "discovery.k8s.io"
      - "networking.k8s.io"
    resources:
      - endpoints
      - endpointslices
      - ingresses
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  # Rules which allow loki.source.kubernetes and loki.source.podlogs to work.
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "monitoring.grafana.com"
    resources:
      - podlogs
    verbs:
      - get
      - list
      - watch
  # Rules which allow mimir.rules.kubernetes to work.
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  # Rules for prometheus.kubernetes.*
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - podmonitors
      - servicemonitors
      - probes
    verbs:
      - get
      - list
      - watch
  # Rules which allow eventhandler to work.
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
# Source: grafana-agent/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RELEASE-NAME-grafana-agent
  labels:
    helm.sh/chart: grafana-agent-0.13.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v0.33.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-grafana-agent
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-grafana-agent
    namespace: grafana-agent
---
# Source: grafana-agent/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-grafana-agent
  labels:
    helm.sh/chart: grafana-agent-0.13.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v0.33.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: RELEASE-NAME
  ports:
    - name: http-metrics
      port: 80
      targetPort: 80
      protocol: "TCP"
    - name: faro
      port: 12347
      targetPort: 12347
      protocol: "TCP"
---
# Source: grafana-agent/templates/controllers/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: RELEASE-NAME-grafana-agent
  labels:
    helm.sh/chart: grafana-agent-0.13.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v0.33.1"
    app.kubernetes.io/managed-by: Helm
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-agent
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-agent
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccount: RELEASE-NAME-grafana-agent
      containers:
        - name: grafana-agent
          image: grafana/agent:v0.33.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/agent/config.river
            - --storage.path=/tmp/agent
            - --server.http.listen-addr=0.0.0.0:80
          env:
            - name: AGENT_MODE
              value: flow
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 80
              name: http-metrics
            - containerPort: 12347
              name: faro
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/agent
        - name: config-reloader
          image: jimmidyson/configmap-reload:v0.8.0
          args:
            - --volume-dir=/etc/agent
            - --webhook-url=http://localhost:80/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/agent
      dnsPolicy: ClusterFirst
      volumes:
        - name: config
          configMap:
            name: RELEASE-NAME-grafana-agent
