#!/bin/sh

set -e

[ -f /etc/default/grafana-agent ] && . /etc/default/grafana-agent

# Initial installation: $1 == configure
# Upgrade: $1 == 2, and configured to restart on upgrade
case "$1" in
    configure)
        [ -z "$GRAFANA_AGENT_USER" ] && GRAFANA_AGENT_USER="grafana-agent"
        [ -z "$GRAFANA_AGENT_GROUP" ] && GRAFANA_AGENT_GROUP="grafana-agent"
        if ! getent group "$GRAFANA_AGENT_GROUP" > /dev/null 2>&1 ; then
            groupadd -r "$GRAFANA_AGENT_GROUP"
        fi
        if ! getent passwd "$GRAFANA_AGENT_USER" > /dev/null 2>&1 ; then
            useradd -m -r -g grafana-agent -d /var/lib/grafana-agent -s /sbin/nologin -c "grafana-agent user" grafana-agent
        fi

        chmod 640 /etc/grafana-agent.yaml
        chown root:$GRAFANA_AGENT_GROUP /etc/grafana-agent.yaml

        if [ -z ${2+x} ] &&  [ "$RESTART_ON_UPGRADE" == "true" ]; then
            if command -v systemctl 2>/dev/null; then
                systemctl daemon-reload
            fi
        fi
esac
