apiVersion: 1

deleteDatasources:
  - name: Cortex

datasources:
- name: Cortex
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex:9009/api/prom
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: tid=(\w+)
        name: TraceID
        url: $${__value.raw}

