version: '3'

services:
  mimir:
    image: grafana/mimir:latest
    volumes:
      - ./mimir:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"
  agent:
    image: grafana/agent:main
    ports:
      - 12345:12345
    volumes:
      - ./flow_configs:/etc/agent-config
    environment:
      AGENT_MODE: "flow"
    entrypoint:
      - /bin/grafana-agent
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent-config/$CONFIG_FILE
  grafana:
    image: grafana/grafana:8.3.3
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
