FROM grafana/agent-build-image:0.30.4-windows as builder
ARG VERSION
ARG RELEASE_BUILD=1

COPY . /src/agent
WORKDIR /src/agent

SHELL ["cmd", "/S", "/C"]

# Creating new layers can be really slow on Windows so we clean up any caches
# we can before moving on to the next step.
RUN ""C:\Program Files\git\bin\bash.exe" -c "RELEASE_BUILD=${RELEASE_BUILD} VERSION=${VERSION} make generate-ui && rm -rf web/ui/node_modules && yarn cache clean --all""
RUN ""C:\Program Files\git\bin\bash.exe" -c "RELEASE_BUILD=${RELEASE_BUILD} VERSION=${VERSION} GO_TAGS='builtinassets' make agent && go clean -cache -modcache""

# Use the smallest container possible for the final image
FROM mcr.microsoft.com/windows/nanoserver:1809

COPY --from=builder /src/agent/build/grafana-agent /bin/grafana-agent
COPY --from=builder /src/agent/cmd/grafana-agent/agent-local-config.yaml /etc/grafana-agent/grafana-agent.yaml

ENTRYPOINT ["/bin/grafana-agent"]
CMD ["--config.file=/etc/grafana-agent/grafana-agent.yaml", "--metrics.wal-directory=/etc/grafana-agent/data"]
