FROM grafana/agent-build-image:0.19.0-windows as builder
ARG VERSION
ARG RELEASE_BUILD=1

COPY . /src/agent
WORKDIR /src/agent

SHELL ["cmd", "/S", "/C"]

RUN ""C:\Program Files\git\bin\bash.exe" -c 'RELEASE_BUILD=${RELEASE_BUILD} VERSION=${VERSION} make agentctl"

# Use the smallest container possible for the final image
FROM mcr.microsoft.com/windows/nanoserver:1809

COPY --from=builder /src/agent/build/grafana-agentctl /bin/grafana-agentctl

ENTRYPOINT ["/bin/grafana-agentctl"]
