name: Feature request
description: Suggest an idea to be added to Grafana Agent.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a bug report for Grafana Agent.

        Please do not use GitHub issues for support questions. If you need help or support, ask a question in [GitHub Discussions](https://github.com/grafana/agent/discussions) or join the `#agent` channel on the [Grafana Slack](https://slack.grafana.com/).
  - type: textarea
    attributes:
      label: Request
      description: What feature do you want?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Why do you need this feature?
    validations:
      required: true
