// Package all imports all known component packages.
package all

import (
	_ "github.com/grafana/agent/internal/component/beyla/ebpf"                               // Import beyla.ebpf
	_ "github.com/grafana/agent/internal/component/discovery/consul"                         // Import discovery.consul
	_ "github.com/grafana/agent/internal/component/discovery/consulagent"                    // Import discovery.consulagent
	_ "github.com/grafana/agent/internal/component/discovery/dns"                            // Import discovery.dns
	_ "github.com/grafana/agent/internal/component/discovery/file"                           // Import discovery.file
	_ "github.com/grafana/agent/internal/component/discovery/http"                           // Import discovery.http
	_ "github.com/grafana/agent/internal/component/faro/receiver"                            // Import faro.receiver
	_ "github.com/grafana/agent/internal/component/local/file"                               // Import local.file
	_ "github.com/grafana/agent/internal/component/local/file_match"                         // Import local.file_match
	_ "github.com/grafana/agent/internal/component/loki/echo"                                // Import loki.echo
	_ "github.com/grafana/agent/internal/component/loki/process"                             // Import loki.process
	_ "github.com/grafana/agent/internal/component/loki/relabel"                             // Import loki.relabel
	_ "github.com/grafana/agent/internal/component/loki/rules/kubernetes"                    // Import loki.rules.kubernetes
	_ "github.com/grafana/agent/internal/component/loki/source/api"                          // Import loki.source.api
	_ "github.com/grafana/agent/internal/component/loki/source/windowsevent"                 // Import loki.source.windowsevent
	_ "github.com/grafana/agent/internal/component/loki/write"                               // Import loki.write
	_ "github.com/grafana/agent/internal/component/mimir/rules/kubernetes"                   // Import mimir.rules.kubernetes
	_ "github.com/grafana/agent/internal/component/module/file"                              // Import module.file
	_ "github.com/grafana/agent/internal/component/module/git"                               // Import module.git
	_ "github.com/grafana/agent/internal/component/module/http"                              // Import module.http
	_ "github.com/grafana/agent/internal/component/module/string"                            // Import module.string
	_ "github.com/grafana/agent/internal/component/otelcol/auth/basic"                       // Import otelcol.auth.basic
	_ "github.com/grafana/agent/internal/component/otelcol/auth/bearer"                      // Import otelcol.auth.bearer
	_ "github.com/grafana/agent/internal/component/otelcol/auth/headers"                     // Import otelcol.auth.headers
	_ "github.com/grafana/agent/internal/component/otelcol/auth/oauth2"                      // Import otelcol.auth.oauth2
	_ "github.com/grafana/agent/internal/component/otelcol/auth/sigv4"                       // Import otelcol.auth.sigv4
	_ "github.com/grafana/agent/internal/component/otelcol/connector/host_info"              // Import otelcol.connector.host_info
	_ "github.com/grafana/agent/internal/component/otelcol/connector/servicegraph"           // Import otelcol.connector.servicegraph
	_ "github.com/grafana/agent/internal/component/otelcol/connector/spanlogs"               // Import otelcol.connector.spanlogs
	_ "github.com/grafana/agent/internal/component/otelcol/connector/spanmetrics"            // Import otelcol.connector.spanmetrics
	_ "github.com/grafana/agent/internal/component/otelcol/exporter/loadbalancing"           // Import otelcol.exporter.loadbalancing
	_ "github.com/grafana/agent/internal/component/otelcol/exporter/logging"                 // Import otelcol.exporter.logging
	_ "github.com/grafana/agent/internal/component/otelcol/exporter/loki"                    // Import otelcol.exporter.loki
	_ "github.com/grafana/agent/internal/component/otelcol/exporter/otlp"                    // Import otelcol.exporter.otlp
	_ "github.com/grafana/agent/internal/component/otelcol/exporter/otlphttp"                // Import otelcol.exporter.otlphttp
	_ "github.com/grafana/agent/internal/component/otelcol/exporter/prometheus"              // Import otelcol.exporter.prometheus
	_ "github.com/grafana/agent/internal/component/otelcol/extension/jaeger_remote_sampling" // Import otelcol.extension.jaeger_remote_sampling
	_ "github.com/grafana/agent/internal/component/otelcol/processor/attributes"             // Import otelcol.processor.attributes
	_ "github.com/grafana/agent/internal/component/otelcol/processor/batch"                  // Import otelcol.processor.batch
	_ "github.com/grafana/agent/internal/component/otelcol/processor/discovery"              // Import otelcol.processor.discovery
	_ "github.com/grafana/agent/internal/component/otelcol/processor/filter"                 // Import otelcol.processor.filter
	_ "github.com/grafana/agent/internal/component/otelcol/processor/memorylimiter"          // Import otelcol.processor.memory_limiter
	_ "github.com/grafana/agent/internal/component/otelcol/processor/probabilistic_sampler"  // Import otelcol.processor.probabilistic_sampler
	_ "github.com/grafana/agent/internal/component/otelcol/processor/resourcedetection"      // Import otelcol.processor.resourcedetection
	_ "github.com/grafana/agent/internal/component/otelcol/processor/span"                   // Import otelcol.processor.span
	_ "github.com/grafana/agent/internal/component/otelcol/processor/tail_sampling"          // Import otelcol.processor.tail_sampling
	_ "github.com/grafana/agent/internal/component/otelcol/processor/transform"              // Import otelcol.processor.transform
	_ "github.com/grafana/agent/internal/component/otelcol/receiver/loki"                    // Import otelcol.receiver.loki
	_ "github.com/grafana/agent/internal/component/otelcol/receiver/opencensus"              // Import otelcol.receiver.opencensus
	_ "github.com/grafana/agent/internal/component/otelcol/receiver/otlp"                    // Import otelcol.receiver.otlp
	_ "github.com/grafana/agent/internal/component/otelcol/receiver/prometheus"              // Import otelcol.receiver.prometheus
	_ "github.com/grafana/agent/internal/component/otelcol/receiver/vcenter"                 // Import otelcol.receiver.vcenter
	_ "github.com/grafana/agent/internal/component/otelcol/receiver/zipkin"                  // Import otelcol.receiver.zipkin
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/blackbox"             // Import prometheus.exporter.blackbox
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/cadvisor"             // Import prometheus.exporter.cadvisor
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/cloudwatch"           // Import prometheus.exporter.cloudwatch
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/consul"               // Import prometheus.exporter.consul
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/dnsmasq"              // Import prometheus.exporter.dnsmasq
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/process"              // Import prometheus.exporter.process
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/self"                 // Import prometheus.exporter.self
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/snmp"                 // Import prometheus.exporter.snmp
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/unix"                 // Import prometheus.exporter.unix
	_ "github.com/grafana/agent/internal/component/prometheus/exporter/windows"              // Import prometheus.exporter.windows
	_ "github.com/grafana/agent/internal/component/prometheus/receive_http"                  // Import prometheus.receive_http
	_ "github.com/grafana/agent/internal/component/prometheus/relabel"                       // Import prometheus.relabel
	_ "github.com/grafana/agent/internal/component/prometheus/remotewrite"                   // Import prometheus.remote_write
	_ "github.com/grafana/agent/internal/component/prometheus/scrape"                        // Import prometheus.scrape
	_ "github.com/grafana/agent/internal/component/pyroscope/ebpf"                           // Import pyroscope.ebpf
	_ "github.com/grafana/agent/internal/component/pyroscope/scrape"                         // Import pyroscope.scrape
	_ "github.com/grafana/agent/internal/component/pyroscope/write"                          // Import pyroscope.write
	_ "github.com/grafana/agent/internal/component/remote/http"                              // Import remote.http
)
