{
 "title": "Agent Tracing Pipeline",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(agent_build_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(agent_build_info, namespace)"
   },
   {
    "name": "container",
    "query": "label_values(agent_build_info, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Received Spans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_receiver_accepted_spans{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}[$__interval])",
     "legendFormat": "{{pod}}-{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Sent Spans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_exporter_sent_spans{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}[$__interval])",
     "legendFormat": "{{pod}}-{{exporter}}"
    }
   ]
  },
  {
   "title": "Exporter Failed Send Spans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_exporter_send_failed_spans{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}[$__interval])",
     "legendFormat": "{{pod}}-{{exporter}}"
    }
   ]
  },
  {
   "title": "Receiver Refused Spans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_receiver_refused_spans{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}[$__interval])",
     "legendFormat": "{{pod}}-{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Dropped Spans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_processor_dropped_spans{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}[$__interval])",
     "legendFormat": "{{pod}}-{{processor}}"
    }
   ]
  }
 ]
}