server:
  log_level: info
  http_listen_port: 12345

prometheus:
  wal_directory: /opt/grafana-agent/data
  global:
    scrape_interval: 15s
  configs:
    - name: grafana-agent
      scrape_configs:
        - job_name: grafana-agent
          static_configs:
            - targets: ['127.0.0.1:12345']
