server:
  log_level: info
  http_listen_port: 12345

prometheus:
  wal_directory: /opt/grafana-agent/data
  global:
    scrape_interval: 5s

integrations:
  agent:
    enabled: true 
  node_exporter:
    enabled: true 
    enable_collectors:
      - systemd
    disable_collectors:
      - powersupplyclass 
  ## Remove the commented out section below and replace REMOTE_WRITE_URL,
  ## REMOTE_WRITE_USERNAME, and REMOTE_WRITE_PASSWORD with the appropriate 
  ## values for your specific Grafana Cloud Prometheus instance.
  prometheus_remote_write:
   - url: https://prometheus-us-central1.grafana.net/api/prom/push 
     basic_auth:
       username: 11946
       password: eyJrIjoiYWM2MmU5YjhiZTNjNTZjZjU0ODVmYjkyNDE5ZGQzOTFjZGFiZmRjYiIsIm4iOiJEZW1vIiwiaWQiOjI2MDcxOH0=
