apiVersion: 1

deleteDatasources:
  - name: Mimir

datasources:
- name: Mimir
  type: prometheus
  access: proxy
  orgId: 1
  url: http://mimir:9009/prometheus
  basicAuth: false
  isDefault: false
  version: 1
  editable: false