server:
  log_level: debug

metrics:
  global:
    scrape_interval: 1m
  configs:
  - name: default
    scrape_configs:
    - job_name: demo.robustperception.io
      static_configs:
      - targets: ['demo.robustperception.io:3000']
        labels:
          app: grafana
      - targets: ['demo.robustperception.io:9090']
        labels:
          app: prometheus
      - targets: ['demo.robustperception.io:9100']
        labels:
          app: node_exporter
      - targets: ['demo.robustperception.io:9093']
        labels:
          app: alertmanager
      - targets: ['demo.robustperception.io:9091']
        labels:
          app: pushgateway
