server:
  log_level: debug

metrics:
  global:
    scrape_interval: 1m
  configs:
  - name: default
    scrape_configs:
      - job_name: grafana
        static_configs:
        - targets: ['demo.robustperception.io:3000']
      - job_name: prometheus
        static_configs:
        - targets: ['demo.robustperception.io:9090']
      - job_name: node_exporter
        static_configs:
        - targets: ['demo.robustperception.io:9100']
      - job_name: alertmanager
        static_configs:
        - targets: ['demo.robustperception.io:9093']
      - job_name: pushgateway
        static_configs:
        - targets: ['demo.robustperception.io:9091']
