FROM grafana/agent-build-image:latest-windows as builder

COPY . /src/agent
WORKDIR /src/agent

SHELL ["cmd", "/C"]

# Make the ui. This little trick is to execute a bash command in windows
RUN powershell "New-Item -Path 'C:\src\agent\make-generate-ui.sh' -ItemType File; \
    Add-Content -Path 'C:\src\agent\make-generate-ui.sh' -Value '#!/bin/bash'; \
    Add-Content -Path 'C:\src\agent\make-generate-ui.sh' -Value 'make generate-ui'"
RUN "C:\Program Files\git\bin\bash.exe" make-generate-ui.sh

# Make the agent. This little trick is to execute a bash command in windows
RUN powershell "New-Item -Path 'C:\src\agent\make-agent.sh' -ItemType File; \
    Add-Content -Path 'C:\src\agent\make-agent.sh' -Value '#!/bin/bash'; \
    Add-Content -Path 'C:\src\agent\make-agent.sh' -Value 'make agent'"
RUN "C:\Program Files\git\bin\bash.exe" make-agent.sh

# Use the smallest container possible for the final image
FROM mcr.microsoft.com/windows/nanoserver:1809

COPY --from=builder /src/agent/build/agent /bin/agent
COPY --from=builder /src/agent/cmd/agent/agent-local-config.yaml /etc/agent/agent.yaml

#ENTRYPOINT "ping -t localhost"
ENTRYPOINT ["/bin/agent"]
CMD ["--config.file=/etc/agent/agent.yaml", "--metrics.wal-directory=/etc/agent/data"]