host_filter: false
scrape_configs:
  - job_name: avalanche-2
    static_configs:
      - targets: ['avalanche-2:9001']
        labels:
          cluster: 'docker_compose'
          origin: 'agent'
          container: 'avalanche-2'
remote_write:
  - url: http://cortex:9009/api/prom/push
