host_filter: false
scrape_configs:
  - job_name: avalanche-4
    static_configs:
      - targets: ['avalanche-4:9001']
        labels:
          cluster: 'docker_compose'
          origin: 'agent'
          container: 'avalanche-4'
remote_write:
  - url: http://cortex:9009/api/prom/push
