version: "3"
services:

  mimir:
    image: grafana/mimir:2.10.4
    volumes:
      - ./configs/mimir:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-gen:
    depends_on:
      - kafka
    build:
      dockerfile: ./internal/cmd/integration-tests/configs/kafka/Dockerfile
      context: ../../..

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  otel-metrics-gen:
    build:
      dockerfile: ./internal/cmd/integration-tests/configs/otel-metrics-gen/Dockerfile
      context: ../../..
    environment:
      - OTEL_EXPORTER_ENDPOINT=${OTEL_EXPORTER_ENDPOINT:-host.docker.internal:4318}

  prom-gen:
    build:
      dockerfile: ./internal/cmd/integration-tests/configs/prom-gen/Dockerfile
      context: ../../..
    ports:
      - "9001:9001"
  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"
