# syntax=docker/dockerfile:1.4

# NOTE: This Dockerfile can only be built using BuildKit. BuiltKit is used by
# default when running `docker buildx build` or when DOCKER_BUILDKIT=1 is set
# in environment variables.

FROM --platform=$BUILDPLATFORM grafana/agent-build-image:0.15.0 as build
ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG RELEASE_BUILD=1
ARG VERSION

# TODO(rfratto): move this to the base image. The base image isn't properly
# specifying the platform to install libbpfcc-dev for so it's a no-op on arm64
# hosts.
RUN apt-get update && apt-get install -qy libbpfcc-dev:amd64

COPY . /src/agent
WORKDIR /src/agent

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    GOOS=$TARGETOS GOARCH=$TARGETARCH GOARM=${TARGETVARIANT#v} \
    RELEASE_BUILD=${RELEASE_BUILD} VERISON=${VERSION} \
    make -f Makefile-v2.mk agentctl

FROM ubuntu:jammy

# Install dependencies needed at runtime. On x86_64 (arm64), libbpfcc is also
# needed for the eBPF integration.
RUN <<EOF
  apt-get update
  apt-get install -qy libsystemd-dev tzdata ca-certificates

  if [ `uname -m` = "x86_64" ]; then
    apt-get install -qy libbpfcc
  fi

  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
EOF

COPY --from=build /src/agent/build/agentctl /bin/agentctl
ENTRYPOINT ["/bin/agentctl"]
