FROM grafana/agent-build-image:0.18.0-windows as builder

COPY . /src/agent
WORKDIR /src/agent

SHELL ["cmd", "/S", "/C"]

RUN powershell "Invoke-Expression ""C:\'Program Files'\git\bin\bash.exe -c 'make agentctl'"""

# Use the smallest container possible for the final image
FROM mcr.microsoft.com/windows/nanoserver:1809

COPY --from=builder /src/agent/build/agentctl /bin/agentctl

ENTRYPOINT ["/bin/agentctl"]
