{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='probe', url='', help='Probe defines monitoring for a set of static targets or ingresses.'),
  '#metadata':: d.obj(help='ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.'),
  metadata: {
    '#withAnnotations':: d.fn(help='Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\n\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\n\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withManagedFields':: d.fn(help="ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like 'ci-cd'. The set of fields is always in the version that the workflow used when modifying the object.", args=[d.arg(name='managedFields', type=d.T.array)]),
    withManagedFields(managedFields): { metadata+: { managedFields: if std.isArray(v=managedFields) then managedFields else [managedFields] } },
    '#withManagedFieldsMixin':: d.fn(help="ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like 'ci-cd'. The set of fields is always in the version that the workflow used when modifying the object.\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='managedFields', type=d.T.array)]),
    withManagedFieldsMixin(managedFields): { metadata+: { managedFields+: if std.isArray(v=managedFields) then managedFields else [managedFields] } },
    '#withName':: d.fn(help='Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\n\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\n\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='SelfLink is a URL representing this object. Populated by the system. Read-only.\n\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release.', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\n\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Probe', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'monitoring.coreos.com/v1',
    kind: 'Probe',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='Specification of desired Ingress selection for target discovery by Prometheus.'),
  spec: {
    '#basicAuth':: d.obj(help='BasicAuth allow an endpoint to authenticate over basic authentication. More info: https://prometheus.io/docs/operating/configuration/#endpoint'),
    basicAuth: {
      '#password':: d.obj(help='The secret in the service monitor namespace that contains the password for authentication.'),
      password: {
        '#withKey':: d.fn(help='The key of the secret to select from.  Must be a valid secret key.', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { basicAuth+: { password+: { key: key } } } },
        '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { basicAuth+: { password+: { name: name } } } },
        '#withOptional':: d.fn(help='Specify whether the Secret or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
        withOptional(optional): { spec+: { basicAuth+: { password+: { optional: optional } } } },
      },
      '#username':: d.obj(help='The secret in the service monitor namespace that contains the username for authentication.'),
      username: {
        '#withKey':: d.fn(help='The key of the secret to select from.  Must be a valid secret key.', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { basicAuth+: { username+: { key: key } } } },
        '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { basicAuth+: { username+: { name: name } } } },
        '#withOptional':: d.fn(help='Specify whether the Secret or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
        withOptional(optional): { spec+: { basicAuth+: { username+: { optional: optional } } } },
      },
    },
    '#bearerTokenSecret':: d.obj(help='Secret to mount to read bearer token for scraping targets. The secret needs to be in the same namespace as the probe and accessible by the Prometheus Operator.'),
    bearerTokenSecret: {
      '#withKey':: d.fn(help='The key of the secret to select from.  Must be a valid secret key.', args=[d.arg(name='key', type=d.T.string)]),
      withKey(key): { spec+: { bearerTokenSecret+: { key: key } } },
      '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { bearerTokenSecret+: { name: name } } },
      '#withOptional':: d.fn(help='Specify whether the Secret or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
      withOptional(optional): { spec+: { bearerTokenSecret+: { optional: optional } } },
    },
    '#prober':: d.obj(help='Specification for the prober to use for probing targets. The prober.URL parameter is required. Targets cannot be probed if left empty.'),
    prober: {
      '#withPath':: d.fn(help='Path to collect metrics from. Defaults to `/probe`.', args=[d.arg(name='path', type=d.T.string)]),
      withPath(path): { spec+: { prober+: { path: path } } },
      '#withScheme':: d.fn(help='HTTP scheme to use for scraping. Defaults to `http`.', args=[d.arg(name='scheme', type=d.T.string)]),
      withScheme(scheme): { spec+: { prober+: { scheme: scheme } } },
      '#withUrl':: d.fn(help='Mandatory URL of the prober.', args=[d.arg(name='url', type=d.T.string)]),
      withUrl(url): { spec+: { prober+: { url: url } } },
    },
    '#targets':: d.obj(help='Targets defines a set of static and/or dynamically discovered targets to be probed using the prober.'),
    targets: {
      '#ingress':: d.obj(help='Ingress defines the set of dynamically discovered ingress objects which hosts are considered for probing.'),
      ingress: {
        '#namespaceSelector':: d.obj(help='Select Ingress objects by namespace.'),
        namespaceSelector: {
          '#withAny':: d.fn(help='Boolean describing whether all namespaces are selected in contrast to a list restricting them.', args=[d.arg(name='any', type=d.T.boolean)]),
          withAny(any): { spec+: { targets+: { ingress+: { namespaceSelector+: { any: any } } } } },
          '#withMatchNames':: d.fn(help='List of namespace names.', args=[d.arg(name='matchNames', type=d.T.array)]),
          withMatchNames(matchNames): { spec+: { targets+: { ingress+: { namespaceSelector+: { matchNames: if std.isArray(v=matchNames) then matchNames else [matchNames] } } } } },
          '#withMatchNamesMixin':: d.fn(help='List of namespace names.\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchNames', type=d.T.array)]),
          withMatchNamesMixin(matchNames): { spec+: { targets+: { ingress+: { namespaceSelector+: { matchNames+: if std.isArray(v=matchNames) then matchNames else [matchNames] } } } } },
        },
        '#selector':: d.obj(help='Select Ingress objects by labels.'),
        selector: {
          '#withMatchExpressions':: d.fn(help='matchExpressions is a list of label selector requirements. The requirements are ANDed.', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressions(matchExpressions): { spec+: { targets+: { ingress+: { selector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } } },
          '#withMatchExpressionsMixin':: d.fn(help='matchExpressions is a list of label selector requirements. The requirements are ANDed.\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
          withMatchExpressionsMixin(matchExpressions): { spec+: { targets+: { ingress+: { selector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } } } },
          '#withMatchLabels':: d.fn(help='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabels(matchLabels): { spec+: { targets+: { ingress+: { selector+: { matchLabels: matchLabels } } } } },
          '#withMatchLabelsMixin':: d.fn(help='matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
          withMatchLabelsMixin(matchLabels): { spec+: { targets+: { ingress+: { selector+: { matchLabels+: matchLabels } } } } },
        },
        '#withRelabelingConfigs':: d.fn(help='RelabelConfigs to apply to samples before ingestion. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config', args=[d.arg(name='relabelingConfigs', type=d.T.array)]),
        withRelabelingConfigs(relabelingConfigs): { spec+: { targets+: { ingress+: { relabelingConfigs: if std.isArray(v=relabelingConfigs) then relabelingConfigs else [relabelingConfigs] } } } },
        '#withRelabelingConfigsMixin':: d.fn(help='RelabelConfigs to apply to samples before ingestion. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='relabelingConfigs', type=d.T.array)]),
        withRelabelingConfigsMixin(relabelingConfigs): { spec+: { targets+: { ingress+: { relabelingConfigs+: if std.isArray(v=relabelingConfigs) then relabelingConfigs else [relabelingConfigs] } } } },
      },
      '#staticConfig':: d.obj(help='StaticConfig defines static targets which are considers for probing. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config.'),
      staticConfig: {
        '#withLabels':: d.fn(help='Labels assigned to all metrics scraped from the targets.', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { targets+: { staticConfig+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='Labels assigned to all metrics scraped from the targets.\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { targets+: { staticConfig+: { labels+: labels } } } },
        '#withRelabelingConfigs':: d.fn(help='RelabelConfigs to apply to samples before ingestion. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config', args=[d.arg(name='relabelingConfigs', type=d.T.array)]),
        withRelabelingConfigs(relabelingConfigs): { spec+: { targets+: { staticConfig+: { relabelingConfigs: if std.isArray(v=relabelingConfigs) then relabelingConfigs else [relabelingConfigs] } } } },
        '#withRelabelingConfigsMixin':: d.fn(help='RelabelConfigs to apply to samples before ingestion. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='relabelingConfigs', type=d.T.array)]),
        withRelabelingConfigsMixin(relabelingConfigs): { spec+: { targets+: { staticConfig+: { relabelingConfigs+: if std.isArray(v=relabelingConfigs) then relabelingConfigs else [relabelingConfigs] } } } },
        '#withStatic':: d.fn(help='Targets is a list of URLs to probe using the configured prober.', args=[d.arg(name='static', type=d.T.array)]),
        withStatic(static): { spec+: { targets+: { staticConfig+: { static: if std.isArray(v=static) then static else [static] } } } },
        '#withStaticMixin':: d.fn(help='Targets is a list of URLs to probe using the configured prober.\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='static', type=d.T.array)]),
        withStaticMixin(static): { spec+: { targets+: { staticConfig+: { static+: if std.isArray(v=static) then static else [static] } } } },
      },
    },
    '#tlsConfig':: d.obj(help='TLS configuration to use when scraping the endpoint.'),
    tlsConfig: {
      '#ca':: d.obj(help='Struct containing the CA cert to use for the targets.'),
      ca: {
        '#configMap':: d.obj(help='ConfigMap containing data to use for the targets.'),
        configMap: {
          '#withKey':: d.fn(help='The key to select.', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { tlsConfig+: { ca+: { configMap+: { key: key } } } } },
          '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { tlsConfig+: { ca+: { configMap+: { name: name } } } } },
          '#withOptional':: d.fn(help='Specify whether the ConfigMap or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { spec+: { tlsConfig+: { ca+: { configMap+: { optional: optional } } } } },
        },
        '#secret':: d.obj(help='Secret containing data to use for the targets.'),
        secret: {
          '#withKey':: d.fn(help='The key of the secret to select from.  Must be a valid secret key.', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { tlsConfig+: { ca+: { secret+: { key: key } } } } },
          '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { tlsConfig+: { ca+: { secret+: { name: name } } } } },
          '#withOptional':: d.fn(help='Specify whether the Secret or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { spec+: { tlsConfig+: { ca+: { secret+: { optional: optional } } } } },
        },
      },
      '#cert':: d.obj(help='Struct containing the client cert file for the targets.'),
      cert: {
        '#configMap':: d.obj(help='ConfigMap containing data to use for the targets.'),
        configMap: {
          '#withKey':: d.fn(help='The key to select.', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { tlsConfig+: { cert+: { configMap+: { key: key } } } } },
          '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { tlsConfig+: { cert+: { configMap+: { name: name } } } } },
          '#withOptional':: d.fn(help='Specify whether the ConfigMap or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { spec+: { tlsConfig+: { cert+: { configMap+: { optional: optional } } } } },
        },
        '#secret':: d.obj(help='Secret containing data to use for the targets.'),
        secret: {
          '#withKey':: d.fn(help='The key of the secret to select from.  Must be a valid secret key.', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { tlsConfig+: { cert+: { secret+: { key: key } } } } },
          '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { tlsConfig+: { cert+: { secret+: { name: name } } } } },
          '#withOptional':: d.fn(help='Specify whether the Secret or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { spec+: { tlsConfig+: { cert+: { secret+: { optional: optional } } } } },
        },
      },
      '#keySecret':: d.obj(help='Secret containing the client key file for the targets.'),
      keySecret: {
        '#withKey':: d.fn(help='The key of the secret to select from.  Must be a valid secret key.', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { tlsConfig+: { keySecret+: { key: key } } } },
        '#withName':: d.fn(help='Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { tlsConfig+: { keySecret+: { name: name } } } },
        '#withOptional':: d.fn(help='Specify whether the Secret or its key must be defined', args=[d.arg(name='optional', type=d.T.boolean)]),
        withOptional(optional): { spec+: { tlsConfig+: { keySecret+: { optional: optional } } } },
      },
      '#withInsecureSkipVerify':: d.fn(help='Disable target certificate validation.', args=[d.arg(name='insecureSkipVerify', type=d.T.boolean)]),
      withInsecureSkipVerify(insecureSkipVerify): { spec+: { tlsConfig+: { insecureSkipVerify: insecureSkipVerify } } },
      '#withServerName':: d.fn(help='Used to verify the hostname for the targets.', args=[d.arg(name='serverName', type=d.T.string)]),
      withServerName(serverName): { spec+: { tlsConfig+: { serverName: serverName } } },
    },
    '#withInterval':: d.fn(help="Interval at which targets are probed using the configured prober. If not specified Prometheus' global scrape interval is used.", args=[d.arg(name='interval', type=d.T.string)]),
    withInterval(interval): { spec+: { interval: interval } },
    '#withJobName':: d.fn(help='The job name assigned to scraped metrics by default.', args=[d.arg(name='jobName', type=d.T.string)]),
    withJobName(jobName): { spec+: { jobName: jobName } },
    '#withModule':: d.fn(help='The module to use for probing specifying how to probe the target. Example module configuring in the blackbox exporter: https://github.com/prometheus/blackbox_exporter/blob/master/example.yml', args=[d.arg(name='module', type=d.T.string)]),
    withModule(module): { spec+: { module: module } },
    '#withScrapeTimeout':: d.fn(help='Timeout for scraping metrics from the Prometheus exporter.', args=[d.arg(name='scrapeTimeout', type=d.T.string)]),
    withScrapeTimeout(scrapeTimeout): { spec+: { scrapeTimeout: scrapeTimeout } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
