{{- if eq .Values.controller.type "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  minReadySeconds: 10
  selector:
    matchLabels:
      {{- include "grafana-agent.selectorLabels" . | nindent 6 }}
  template:
    {{- include "grafana-agent.pod-template" . | nindent 4 }}
  {{- with .Values.controller.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
