server:
  log_level: debug
  http_listen_port: 12345

tempo:
  receivers:
    jaeger:
      protocols:
        thrift_http: 
  remote_write:
    url: otel-collector:55680
    insecure: true
    basic_auth:
      username: blerg
      password: superblerg
    batch:
      timeout: 5s
      send_batch_size: 100
    queue:
      retry_on_failure: true

prometheus:
  global:
    scrape_interval: 5s
  configs:
    - name: test
      host_filter: false
      scrape_configs:
        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345']
              labels:
                cluster: 'docker_compose'
                origin: 'agent'
                container: 'agent'
      remote_write:
        - url: http://cortex:9009/api/prom/push


