server:
  log_level: debug
  http_listen_port: 12345

tempo:
  receivers:
    jaeger:
      protocols:
        thrift_http: 
  remote_write:
    url: otel-collector:55680
    insecure: true
    basic_auth:
      username: blerg
      password: superblerg
    batch:
      timeout: 5s
      send_batch_size: 100
    queue:
      retry_on_failure: true