# jpe - where to put this

server:
  log_level: debug
  http_listen_port: 12345

tempo:
  exporters:
    otlp:
      endpoint: doesntexist:12345
  extensions:
    health_check: {}
    pprof: {}
    zpages: {}
  processors:
    batch:
      send_batch_size: 1024
      timeout: 5s
  receivers:
    jaeger:
      protocols:
        grpc: null
  service:
    extensions:
    - pprof
    - zpages
    - health_check
    pipelines:
      traces:
      exporters:
      - otlp
      processors:
      - batch
      receivers:
      - jaeger
