## example-loki.yaml contains a tiny Loki deployment used for testing the
## Grafana Agent Operator.

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: default
  labels:
    app: loki
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.2.1
        args:
          - --config.file=/etc/loki/config.yml
          - --server.http-listen-port=8080
        ports:
          - name: http-metrics
            containerPort: 9090
        volumeMounts:
          - mountPath: /etc/loki
            name: config
            readOnly: true
          - mountPath: /var/lib/data
            name: data
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: default
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: default
  labels:
    app: loki
data:
  config.yml: |
    auth_enabled: false
    server:
      graceful_shutdown_timeout: 5m
      http_server_idle_timeout: 120s
      grpc_server_max_recv_msg_size: 25165824
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 24h
    ingester:
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 1
      lifecycler:
        address: 127.0.0.1
        final_sleep: 0s
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    schema_config:
      configs:
      - from: 2021-07-16
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    storage_config:
      boltdb:
        directory: /var/lib/data/index
      filesystem:
        directory: /var/lib/data/chunks
    chunk_store_config:
      max_look_back_period: 0
    table_manager:
      retention_deletes_enabled: true
      retention_period: 48h
