// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package metricspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScraperClient is the client API for Scraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScraperClient interface {
	// ScrapeTargets assigns a set of targets to a Scraper. ScrapeTargets may be
	// called multiple times from multiple distinct callers. See the
	// doucmentation for ScrapeTargetsRequest for more information.
	ScrapeTargets(ctx context.Context, in *ScrapeTargetsRequest, opts ...grpc.CallOption) (*ScrapeTargetsResponse, error)
}

type scraperClient struct {
	cc grpc.ClientConnInterface
}

func NewScraperClient(cc grpc.ClientConnInterface) ScraperClient {
	return &scraperClient{cc}
}

func (c *scraperClient) ScrapeTargets(ctx context.Context, in *ScrapeTargetsRequest, opts ...grpc.CallOption) (*ScrapeTargetsResponse, error) {
	out := new(ScrapeTargetsResponse)
	err := c.cc.Invoke(ctx, "/metrics.agent.grafana.v1.Scraper/ScrapeTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperServer is the server API for Scraper service.
// All implementations must embed UnimplementedScraperServer
// for forward compatibility
type ScraperServer interface {
	// ScrapeTargets assigns a set of targets to a Scraper. ScrapeTargets may be
	// called multiple times from multiple distinct callers. See the
	// doucmentation for ScrapeTargetsRequest for more information.
	ScrapeTargets(context.Context, *ScrapeTargetsRequest) (*ScrapeTargetsResponse, error)
	mustEmbedUnimplementedScraperServer()
}

// UnimplementedScraperServer must be embedded to have forward compatible implementations.
type UnimplementedScraperServer struct {
}

func (UnimplementedScraperServer) ScrapeTargets(context.Context, *ScrapeTargetsRequest) (*ScrapeTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScrapeTargets not implemented")
}
func (UnimplementedScraperServer) mustEmbedUnimplementedScraperServer() {}

// UnsafeScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScraperServer will
// result in compilation errors.
type UnsafeScraperServer interface {
	mustEmbedUnimplementedScraperServer()
}

func RegisterScraperServer(s grpc.ServiceRegistrar, srv ScraperServer) {
	s.RegisterService(&Scraper_ServiceDesc, srv)
}

func _Scraper_ScrapeTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServer).ScrapeTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrics.agent.grafana.v1.Scraper/ScrapeTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServer).ScrapeTargets(ctx, req.(*ScrapeTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scraper_ServiceDesc is the grpc.ServiceDesc for Scraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.agent.grafana.v1.Scraper",
	HandlerType: (*ScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScrapeTargets",
			Handler:    _Scraper_ScrapeTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metricspb.proto",
}
