---
kind: pipeline
name: Check Linux build image
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - docker buildx build -t grafana/agent-build-image:latest ./build-image
  image: docker
  name: Build
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
    include:
    - pull_request
  paths:
    include:
    - build-image/**
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Create Linux build image
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - export IMAGE_TAG=${DRONE_TAG##build-image/v}
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --driver docker-container --use
  - docker buildx build --push --platform linux/amd64,linux/arm64 -t grafana/agent-build-image:$IMAGE_TAG
    ./build-image
  environment:
    DOCKER_LOGIN:
      from_secret: DOCKER_LOGIN
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  image: docker
  name: Build
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
  - tag
  ref:
  - refs/tags/build-image/v*
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Check Windows build image
platform:
  arch: amd64
  os: windows
  version: "1809"
steps:
- commands:
  - docker build -t grafana/agent-build-image:latest ./build-image/windows
  image: docker:windowsservercore-1809
  name: Build
  volumes:
  - name: docker
    path: //./pipe/docker_engine/
trigger:
  event:
    include:
    - pull_request
  paths:
    include:
    - build-image/**
type: docker
volumes:
- host:
    path: //./pipe/docker_engine/
  name: docker
---
kind: pipeline
name: Create Windows build image
platform:
  arch: amd64
  os: windows
  version: "1809"
steps:
- commands:
  - $IMAGE_TAG="${DRONE_TAG##build-image/v}-windows"
  - docker login -u $Env:DOCKER_LOGIN -p $Env:DOCKER_PASSWORD
  - docker build -t grafana/agent-build-image:$IMAGE_TAG ./build-image/windows
  - docker push grafana/agent-build-image:$IMAGE_TAG
  environment:
    DOCKER_LOGIN:
      from_secret: DOCKER_LOGIN
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  image: docker:windowsservercore-1809
  name: Build
  volumes:
  - name: docker
    path: //./pipe/docker_engine/
trigger:
  event:
  - tag
  ref:
  - refs/tags/build-image/v*
type: docker
volumes:
- host:
    path: //./pipe/docker_engine/
  name: docker
---
kind: pipeline
name: Lint
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make lint
  image: grafana/agent-build-image:0.20.0
  name: Lint
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Test
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - K8S_USE_DOCKER_NETWORK=1 make test
  image: grafana/agent-build-image:0.20.0
  name: Run Go tests
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
  - pull_request
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Test (Windows)
platform:
  arch: amd64
  os: windows
  version: "1809"
steps:
- commands:
  - go test -tags="nodocker,nonetwork" ./...
  image: grafana/agent-build-image:0.20.0-windows
  name: Run Go tests
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Check Linux container (grafana/agent)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make agent-image
  image: grafana/agent-build-image:0.20.0
  name: Build container
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
  - pull_request
  paths:
  - cmd/grafana-agent/Dockerfile
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Check Linux container (grafana/agentctl)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make agentctl-image
  image: grafana/agent-build-image:0.20.0
  name: Build container
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
  - pull_request
  paths:
  - cmd/grafana-agentctl/Dockerfile
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Check Linux container (grafana/agent-operator)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make operator-image
  image: grafana/agent-build-image:0.20.0
  name: Build container
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
  - pull_request
  paths:
  - cmd/grafana-agent-operator/Dockerfile
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Check Windows containers
platform:
  arch: amd64
  os: windows
  version: "1809"
steps:
- commands:
  - git config --global --add safe.directory C:/drone/src/
  - '& "C:/Program Files/git/bin/bash.exe" -c ./tools/ci/docker-containers-windows'
  image: grafana/agent-build-image:0.20.0-windows
  name: Build container
  volumes:
  - name: docker
    path: //./pipe/docker_engine/
trigger:
  event:
  - pull_request
  paths:
  - '**/Dockerfile.windows'
type: docker
volumes:
- host:
    path: //./pipe/docker_engine/
  name: docker
---
kind: pipeline
name: Build agent (Linux amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=amd64 GOARM= make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Linux arm64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm64 GOARM= make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Linux armv6)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm GOARM=6 make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Linux armv7)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm GOARM=7 make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Linux ppc64le)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=ppc64le GOARM= make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (macOS Intel)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=darwin GOARCH=amd64 GOARM= make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (macOS Apple Silicon)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=darwin GOARCH=arm64 GOARM= make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Windows amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=windows GOARCH=amd64 GOARM= make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (FreeBSD amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=freebsd GOARCH=amd64 GOARM= make agent
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (Linux amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=amd64 GOARM= make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (Linux arm64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm64 GOARM= make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (Linux armv6)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm GOARM=6 CGO_ENABLED=0 make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (Linux armv7)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (Linux ppc64le)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=ppc64le GOARM= make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (macOS Intel)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=darwin GOARCH=amd64 GOARM= make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (macOS Apple Silicon)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=darwin GOARCH=arm64 GOARM= make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (Windows amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=windows GOARCH=amd64 GOARM= make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agentctl (FreeBSD amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=freebsd GOARCH=amd64 GOARM= make agentctl
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (Linux amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=amd64 GOARM= make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (Linux arm64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm64 GOARM= make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (Linux armv6)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm GOARM=6 make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (Linux armv7)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=arm GOARM=7 make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (Linux ppc64le)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=linux GOARCH=ppc64le GOARM= make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (macOS Intel)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=darwin GOARCH=amd64 GOARM= make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (macOS Apple Silicon)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=darwin GOARCH=arm64 GOARM= make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (Windows amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=windows GOARCH=amd64 GOARM= make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build operator (FreeBSD amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - GOOS=freebsd GOARCH=amd64 GOARM= make operator
  image: grafana/agent-build-image:0.20.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Publish Linux Docker containers
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - mkdir -p $HOME/.docker
  - printenv GCR_CREDS > $HOME/.docker/config.json
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --driver docker-container --use
  - ./tools/ci/docker-containers
  - docker buildx rm multiarch
  environment:
    DOCKER_LOGIN:
      from_secret: DOCKER_LOGIN
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    GCR_CREDS:
      from_secret: gcr_admin
  image: grafana/agent-build-image:0.20.0
  name: Build containers
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  ref:
  - refs/heads/main
  - refs/tags/v*
  - refs/heads/dev.*
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
depends_on:
- Publish Linux Docker containers
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: Deploy to deployment_tools
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - apk update && apk add git
  - echo "$(sh ./tools/image-tag)" > .tag-only
  - echo "grafana/agent:$(sh ./tools/image-tag)" > .image-tag
  image: alpine
  name: Create .image-tag
- image: us.gcr.io/kubernetes-dev/drone/plugins/updater
  name: Update deployment_tools
  settings:
    config_json: |
      {
        "destination_branch": "master",
        "pull_request_branch_prefix": "cd-agent",
        "pull_request_enabled": false,
        "pull_request_team_reviewers": [
          "agent-squad"
        ],
        "repo_name": "deployment_tools",
        "update_jsonnet_attribute_configs": [
          {
            "file_path": "ksonnet/environments/kowalski/dev-us-central-0.kowalski-dev/main.jsonnet",
            "jsonnet_key": "agent_image",
            "jsonnet_value_file": ".image-tag"
          },
          {
            "file_path": "ksonnet/environments/grafana-agent/waves/agent.libsonnet",
            "jsonnet_key": "dev_canary",
            "jsonnet_value_file": ".image-tag"
          }
        ]
      }
    github_token:
      from_secret: gh_token
trigger:
  ref:
  - refs/heads/main
type: docker
---
kind: pipeline
name: Publish Windows Docker containers
platform:
  arch: amd64
  os: windows
  version: "1809"
steps:
- commands:
  - git config --global --add safe.directory C:/drone/src/
  - '& "C:/Program Files/git/bin/bash.exe" -c ./tools/ci/docker-containers-windows'
  environment:
    DOCKER_LOGIN:
      from_secret: DOCKER_LOGIN
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  image: grafana/agent-build-image:0.20.0-windows
  name: Build containers
  volumes:
  - name: docker
    path: //./pipe/docker_engine/
trigger:
  ref:
  - refs/heads/main
  - refs/tags/v*
  - refs/heads/dev.*
type: docker
volumes:
- host:
    path: //./pipe/docker_engine/
  name: docker
---
depends_on:
- Publish Linux Docker containers
- Publish Windows Docker containers
kind: pipeline
name: Publish release
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - make -j4 RELEASE_BUILD=1 VERSION=${DRONE_TAG} dist
  - |
    VERSION=${DRONE_TAG} RELEASE_DOC_TAG=$(echo ${DRONE_TAG} | awk -F '.' '{print $1"."$2}') ./tools/release
  environment:
    DOCKER_LOGIN:
      from_secret: DOCKER_LOGIN
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    GITHUB_TOKEN:
      from_secret: GITHUB_KEY
    GPG_PASSPHRASE:
      from_secret: gpg_passphrase
    GPG_PRIVATE_KEY:
      from_secret: gpg_private_key
    GPG_PUBLIC_KEY:
      from_secret: gpg_public_key
  image: grafana/agent-build-image:0.20.0
  name: Publish release
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  ref:
  - refs/tags/v*
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: .dockerconfigjson
  path: infra/data/ci/gcr-admin
kind: secret
name: gcr_admin
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: gh_token
---
get:
  name: public-key
  path: infra/data/ci/packages-publish/gpg
kind: secret
name: gpg_public_key
---
get:
  name: private-key
  path: infra/data/ci/packages-publish/gpg
kind: secret
name: gpg_private_key
---
get:
  name: passphrase
  path: infra/data/ci/packages-publish/gpg
kind: secret
name: gpg_passphrase
---
kind: signature
hmac: 64ab9b77f80ee505a0e87c2a90d7d0c03f502c334720cf0308e18197160575f9

...
