---
kind: pipeline
name: Lint
platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: golangci/golangci-lint:v1.37.1
  commands:
  - apt-get update -y && apt-get install -y libsystemd-dev
  - make lint
---
kind: pipeline
type: docker
name: Dist
platform:
  os: linux
  arch: amd64

steps:
- name: distribute
  image: rfratto/seego
  commands:
  - apt-get update &&  apt-get install -y rubygems rpm nsis
  - gem install --no-document fpm
  - mkdir -p /usr/local/go/bin
  - wget -q https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
  - rm go1.16.5.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - make BUILD_IN_CONTAINER=false RELEASE_TAG=v0.0.0 dist
---
kind: pipeline
type: docker
name: Release
platform:
  os: linux
  arch: amd64
trigger:
  event:
  - tag

steps:
- name: create-release
  image: rfratto/seego
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
  - curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
  - apt-get update &&  apt-get install -y rubygems rpm nsis docker-ce docker-ce-cli containerd.io
  - gem install --no-document fpm
  - mkdir -p /usr/local/go/bin
  - wget -q https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
  - rm go1.16.5.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - GO111MODULE=on go get -u github.com/mitchellh/gox github.com/tcnksm/ghr
  - export PATH="$(go env GOPATH)/bin:$PATH"
  - RELEASE_TAG=$DRONE_TAG
  - make -j4 BUILD_IN_CONTAINER=false RELEASE_BUILD=true RELEASE_TAG=$RELEASE_TAG publish
- name: publish
  image: plugins/github-release
  environment:
    GITHUB_KEY:
      from_secret: GITHUB_KEY
  settings:
    api_key: $GITHUB_KEY
    files: /drone/src/dist/*
    draft: true
  when:
    event: tag

volumes:
- name: docker
  host: 
    path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: Containerize
platform:
  os: linux
  arch: amd64

steps:
- name: Build Containers
  image: docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  environment:
    DOCKER_LOGIN:
      from_secret: DOCKER_LOGIN
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - apk update && apk add make bash wget git qemu
  - wget -q https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
  - mkdir -p ~/.docker/cli-plugins 
  - cp buildx-v0.5.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --driver docker-container --use
  - make CROSS_BUILD=true RELEASE_BUILD=true agent-image
  - make CROSS_BUILD=true RELEASE_BUILD=true agentctl-image

volumes:
- name: docker
  host: 
    path: /var/run/docker.sock
---
kind: signature
hmac: 2c5a38030ab9a70a1d3cdaf436a746c0844fe40878ba2077dd9245238699ebe3

...
