#!/usr/bin/env bash
set -o errexit
set -o pipefail

if [ ! -z "${RELEASE_TAG}" ]; then
  echo ${RELEASE_TAG}
  exit 0
fi

set -o nounset

VERSION=$(cat VERSION)

if [[ -z $(git status -s) ]]; then
  # There are no changes; report version as VERSION-devel+SHA.
  SHA=$(git rev-parse --short HEAD)
  echo ${VERSION}-devel+${SHA}
else
  # Git is dirty; tag as VERSION-devel+wip.
  echo ${VERSION}-devel+wip
fi
