#!/usr/bin/env bash

set -ef -o pipefail

tag="${RELEASE_TAG:-$(git describe --exact-match 2> /dev/null || true)}"

if [[ -z "${tag}" ]]; then
    echo "ERROR: no tag found" >&2
    exit 1
fi

echo "${tag//v/}"
