#!/usr/bin/env bash

ROOT=$(git rev-parse --show-toplevel)

find $ROOT -type f \
  -not -path "$ROOT/build/*" \
  -not -path "$ROOT/dist/*" \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -not -path '*/.rpmdb/*' \
  -not -path '*vendor/*' \
  -exec sed -i '.sed.bk' 's#grafana/agent:[^\s]+#grafana/agent:FOOBAR#g' {} \;

find $ROOT -type f \
  -path '*.sed.bk' \
  -exec rm "{}" \;
