#!/usr/bin/env bash
ghr \
  -t "${GITHUB_TOKEN}" \
  -u "grafana" \
  -r "agent" \
  -c "${GITHUB_SHA}" \
  -b="$(cat ./tools/release-note.md | envsubst)" \
  -delete -draft \
  "${RELEASE_TAG}" ./dist/
