#!/usr/bin/env bash
#
# This script should be run from the root of the repository.

# Zip up agent* binaries to reduce the download size. agent* binaries include
# everything *except* for the deb/rpm assets, which are named grafana-agent*.
for i in dist/agent*; do
  zip -j -m $$i.zip $$i
done

# Sign the RPM packages. DEB packages aren't signed.
./packaging/rpm/gpg-sign.sh

# Get the SHA256SUMS before continuing.
pushd dist && sha256sum * > SHA256SUMS && popd

ghr \
  -t "${GITHUB_TOKEN}" \
  -u "grafana" \
  -r "agent" \
  -c "${GITHUB_SHA}" \
  -b="$(cat ./tools/release-note.md | envsubst)" \
  -delete -draft \
  "${RELEASE_TAG}" ./dist/
