#!/bin/sh

set -e

# shellcheck disable=SC1091
[ -f /etc/sysconfig/grafana-agent ] && . /etc/sysconfig/grafana-agent

# final uninstallation $1=0
# If other copies of this RPM are installed, then $1>0

if [ "$1" -eq 0 ] ; then
    if [ -x /bin/systemctl ] ; then
        /bin/systemctl stop grafana-agent.service > /dev/null 2>&1 || :
    elif [ -x /etc/init.d/grafana-agent ] ; then
        /etc/init.d/grafana-agent stop
    elif [ -x /etc/rc.d/init.d/grafana-agent ] ; then
        /etc/rc.d/init.d/grafana-agent stop
    fi
fi
exit 0
