name: Backport PR Creator
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run backport
        uses: ./actions/backport
        with:
          labelsToAdd: backport
          # The provided token needs read permissions for organization members if you want to remove the default reviewers.
          removeDefaultReviewers: false
          title: "[{{base}}] {{originalTitle}}"
          token: ${{ secrets.GITHUB_TOKEN }}
