jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          persist-credentials: false

      - name: Safe PoC - show access to token
        run: echo "This would expose the token: ${{ secrets.GITHUB_TOKEN }}"

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Run backport
        uses: ./actions/backport
        with:
          labelsToAdd: backport
          removeDefaultReviewers: false
          title: "[{{base}}] {{originalTitle}}"
          token: ${{ secrets.GITHUB_TOKEN }}
