name: Test Versioned Files
on: pull_request
permissions:
  contents: read
jobs:
  regenerate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Regenerate versioned files
        run: |
          make generate-versioned-files
          if ! git diff --exit-code; then
            echo "Newly generated versioned files differ from those checked in. Make sure to only update the templates manually and run 'make generate-versioned-files'!" >&2
            exit 1
          fi
