name: Check Windows build image

on:
  pull_request:
    paths:
      - 'build-image/windows/**'

jobs:
  check-windows-build-image:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test Windows build image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: grafana/agent-build-image
          tags: latest
          registry: docker.io
          pushImage: false
          dockerfile: ./build-image/windows/Dockerfile