name: Check Windows build image

on:
  pull_request:
    paths:
      - 'build-image/windows/**'
      - '.github/workflows/check-windows-build-image.yml'

permissions:
  contents: read

jobs:
  check-windows-build-image:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Create test Windows build image
        uses: mr-smithers-excellent/docker-build-push@59523c638baec979a74fea99caa9e29d97e5963c # v6
        with:
          image: grafana/agent-build-image
          tags: latest
          registry: docker.io
          pushImage: false
          dockerfile: ./build-image/windows/Dockerfile
