name: Main CI

on:
  push:
    branches: [main]
  workflow_call: # TODO: remove testing hook before merging

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  test-crds:
    uses: ./.github/workflows/test-crds.yml

  test-dashboards:
    uses: ./.github/workflows/test-dashboards.yml

  crosscompile:
    uses: ./.github/workflows/crosscompile.yml

  check-containers:
    uses: ./.github/workflows/check-containers.yml
