name: "publish-technical-documentation-next"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/sources/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Build technical documentation"
        run: >
          docker run
          --volume "${PWD}/docs/sources:/hugo/content/docs/agent/latest"
          --env HUGO_REFLINKSERRORLEVEL=ERROR
          --rm grafana/docs-base:latest
          /bin/bash -c 'echo -e "---\\nredirectURL: /docs/agent/latest/\\ntype: redirect\\nversioned: true\\n---\\n" > /hugo/content/docs/agent/_index.md && make hugo' 

  sync:
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: "Checkout Agent repo"
      uses: actions/checkout@v4

    - name: "Clone website-sync Action"
      # WEBSITE_SYNC_TOKEN is a fine-grained GitHub Personal Access Token that expires.
      # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
      # GitHub administrator to update the organization secret.
      # The IT helpdesk can update the organization secret.
      run: "git clone --single-branch --no-tags --depth 1 -b master https://grafanabot:${{ secrets.WEBSITE_SYNC_TOKEN }}@github.com/grafana/website-sync ./.github/actions/website-sync"

    - name: "Publish to website repository (next)"
      uses: ./.github/actions/website-sync
      id: "publish_next"
      with:
        repository: grafana/website
        branch: master
        host: github.com
        # PUBLISH_TO_WEBSITE_TOKEN is a fine-grained GitHub Personal Access Token that expires.
        # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
        # GitHub administrator to update the organization secret.
        # The IT helpdesk can update the organization secret.
        github_pat: "grafanabot:${{ secrets.PUBLISH_TO_WEBSITE_TOKEN }}"
        source_folder: docs/sources
        target_folder: 'content/docs/agent/next'
        allow_no_changes: true
    - shell: bash
      run: |
        test -n "${{ steps.publish_next.outputs.commit_hash }}"
        test -n "${{ steps.publish_next.outputs.working_directory }}"
