name: "publish-technical-documentation-next"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/sources/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Build technical documentation"
        run: |
          docker run -v ${PWD}/docs/sources:/hugo/content/docs/agent/latest -e HUGO_REFLINKSERRORLEVEL=ERROR --rm grafana/docs-base:latest /bin/bash -c 'make hugo'

  sync:
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: "Checkout Agent repo"
      uses: actions/checkout@v3

    - name: "Clone website-sync Action"
      # WEBSITE_SYNC_AGENT is a fine-grained GitHub Personal Access Token that expires.
      # It must be updated in the grafanabot GitHub account.
      run: "git clone --single-branch --no-tags --depth 1 -b master https://grafanabot:${{ secrets.WEBSITE_SYNC_AGENT }}@github.com/grafana/website-sync ./.github/actions/website-sync"

    - name: "Publish to website repository (next)"
      uses: ./.github/actions/website-sync
      id: "publish_next"
      with:
        repository: grafana/website
        branch: master
        host: github.com
        # PUBLISH_TO_WEBSITE_AGENT is a fine-grained GitHub Personal Access Token that expires.
        # It must be updated in the grafanabot GitHub account.
        github_pat: "grafanabot:${{ secrets.PUBLISH_TO_WEBSITE_AGENT }}"
        source_folder: docs/sources
        target_folder: 'content/docs/agent/next'
    - shell: bash
      run: |
        test -n "${{ steps.publish_next.outputs.commit_hash }}"
        test -n "${{ steps.publish_next.outputs.working_directory }}"
