name: publish-technical-documentation-next

on:
  push:
    branches:
      - main
    paths:
      - "docs/sources/**"
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/agent'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
        # This internal action's version is left as a tag instead of a pinned hash because renovate
        # does not support this type of tag/version format without custom configuration.
      - uses: grafana/writers-toolkit/publish-technical-documentation@9aed4f7c5b3caa1b58d72ee39232333407d4acbf # publish-technical-documentation/v1
        with:
          website_directory: content/docs/agent/next
