name: Update Windows build image

on:
  workflow_call:
  push:
    tags:
      - 'build-image/v*'

permissions:
  contents: read

env:
  should_push_image: ${{ github.event_name != 'workflow_call' }}

jobs:
  check-windows-build-image:
    runs-on: windows-2019
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Login to Docker Hub
        if: env.should_push_image == 'true'
        uses: docker/login-action@1f401f745bf57e30b3a2800ad308a87d2ebdf14b # v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }} # TODOJOE: update to vault
          password: ${{ secrets.DOCKER_PASSWORD }} # TODOJOE: update to vault

      - name: Extract image tag
        id: extract_tag
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/build-image/v* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/build-image/v}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build/push Windows build image
        uses: mr-smithers-excellent/docker-build-push@59523c638baec979a74fea99caa9e29d97e5963c # v6
        with:
          image: grafana/agent-build-image
          tags: ${{ steps.extract_tag.outputs.IMAGE_TAG }}-windows
          registry: docker.io
          pushImage: ${{ env.should_push_image == 'true' }}
          dockerfile: ./build-image/windows/Dockerfile
